#!/bin/bash
dmidecode -t 17 | awk \
	'BEGIN { FS=":"; OFS=" " } \
	/Size|Form Factor|Configured Memory Speed|Manufacturer/  \
	{ gsub(/^[ \t]+/,"",$2); \
	if ($1 == "	Size") {$2="x "$2}; \
	if ($1 == "	Form Factor") {$2="x "$2}; \
	if ($1 == "	Configured Memory Speed") {$2="x "$2}; \
	if ($1 == "	Manufacturer") {$2="x "$2}; \
	line = (line ? line OFS : "") $2 }\
	
    /^$/ \
    { \
        tick[line]++ ; \
        line="" ; \
    }  \
    END { \
        for (saveline1 in tick) \
            if (saveline1!=null) print tick[saveline1],saveline1 \
        } \
    '  | grep -iv "no module"